### ISSUE TITLE
Question regarding pointnet2

### ISSUE THREAD

**Issue by IsakIngebrigtsen** [eduardohenriquearnold/fastreg#2]
Hey, 
it was a really good paper you and your team made regarding this algorithm, and I thinking of using fastreg in my master thesis as a way to improve navigation in a vehicle that has lidar implemented but not sufficient GNSS. 

I'm wondering in the setup.py file you import "pointnet2_cuda". I cant find this file anywhere in the filestructure, and was wondering if that was correct?

Kind regards 
Isak Foss Ingebrigtsen

**Comment by eduardohenriquearnold** [comment]
Hi Isak,

`pointnet2_cuda` is the name of the extension being built. If you run 
```bash
cd lib/pointnet2/
python setup.py install
````
the extension should be compiled.

Note that this requires the CUDA toolkit to be installed. You can check if this is the case by checking that the following command works: `nvcc --version`.

**Comment by eduardohenriquearnold** [comment]
I'm closing this issue, please re-open if you find other issues.
